blank_issues_enabled: false
contact_links:
  - name: ğŸ“œ å®˜æ–¹æ–‡æ¡£ | GO Ldap Admin Doc
    url: http://ldapdoc.eryajf.net
    about: å…³äºé¡¹ç›®çš„åŠŸèƒ½ç”¨æ³•ä»¥åŠè®¾è®¡è€ƒé‡ï¼Œéƒ½ä¼šåœ¨å®˜ç½‘è¿›è¡Œå‘ˆç°ï¼Œæäº¤é—®é¢˜ä¹‹å‰ï¼Œè¯·å…ˆé˜…è¯»å®˜æ–¹æ–‡æ¡£ï¼Œå¦‚æœè¿˜ä¸èƒ½æ»¡è¶³ï¼Œåˆ™å†æé—®é¢˜ã€‚ | Regarding the functional usage and design considerations of the project, they will be presented on the official website. Before submitting the question, please read the official document first. If it is not satisfied, you will ask the question.
  - name: ğŸ‘€ Githubè®ºå› | GitHub Discussions
    url: https://github.com/eryajf/go-ldap-admin/discussions
    about: å¦‚æœæ‚¨çš„é—®é¢˜ä¸æ˜¯åŠŸèƒ½æˆ–è€…é”™è¯¯ï¼Œè¯·è½¬åˆ°è®¨è®ºé¢æ¿å¹¶åœ¨æäº¤ä¹‹å‰æ£€ç´¢æ‚¨çš„é—®é¢˜æ˜¯å¦å·²ç»å­˜åœ¨ã€‚ | If your question is not a feature or a bug, please go to the discussion panel and retrieve if your question already exists before submitting.
